version: '3.4'

services:
  finance:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    restart: always
    environment:
      ENV: develop
    ports:
      - $HTTP_PORT:$HTTP_PORT
    volumes:
      - .:/go/src/
    depends_on:
      - postgres
    networks:
      - finance
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  postgres:
    image: postgres:15
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    networks:
      - finance
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - finance
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

volumes:
  data:
    driver: local

networks:
  finance:
    driver: bridge
